session: "JSON"

engines:
  session:
    JSON:
      session_dir: "/tmp/sessions"

plugins:
  Auth::Extensible:
    realms:
      login:
        disable_roles: 1
        provider: "App::RPi::EnvUI::Auth"


